### ISSUE TITLE
ติดตั้งแล้ว มันว่างเปล่าเลยครับ

### ISSUE THREAD

**Issue by mayskyfire** [goragod/oas#1]
![screen shot 2560-10-02 at 11 04 42](https://user-images.githubusercontent.com/12538571/31063988-09eb906e-a762-11e7-917d-5208b06a1214.png)
![screen shot 2560-10-02 at 11 04 49](https://user-images.githubusercontent.com/12538571/31063993-0f0b3a7c-a762-11e7-9251-34329b538de7.png)

**Comment by goragodwiriya** [comment]
https://www.kotchasan.com/forum.html?wbid=3787
