### ISSUE TITLE
ช่อง "จำนวนเงิน" ในใบเสนอราคาช่องสุดท้ายไม่ได้แสดงราคาหลังส่วนลดครับ

### ISSUE THREAD

**Issue by appdisqus** [goragod/oas#2]
สวัสดีครับคุณ @goragod 

ก่อนอื่นขอบคุณมากๆ สำหรับ OAS นะครับ มีประโยชน์และเพียงพอกับที่พวกผมกำลังมองหาเลยครับ แต่ทั้งนี้ ณ ตอนนี้เจอปัญหาหนึ่งเรื่องคือช่อง "จำนวนเงิน" ในเอกสารมันไม่แสดงราคาหลังส่วนลดนะครับ โดยไม่ว่าส่วนลดต่อรายการจะเป็นอย่างไร ช่องจำนวนเงินจะแสดงราคาเหมือนยังไม่ได้มีส่วนลดเพิ่มเข้าไป แต่ตอนใส่ส่วนลดในหลังบ้านนั้นช่องจำนวนเงินมีการอัพเดตอย่างถูกต้องครับ มีปัญหาเฉพาะในหน้าที่จะสั่งพิมพ์ออกมา ตามตัวอย่างที่แนบมาเลยครับ

![screen shot 2561-01-03 at 15 42 26](https://user-images.githubusercontent.com/35060517/34513974-8ea25f7a-f09d-11e7-86b2-1d8552fd3cfb.png)

ทั้งนี้ Grand Total จะแสดงยอดที่ถูกต้องหลังหักส่วนลดแล้วครับ

ขอบคุณและรบกวนชี้แนะด้วยนะครับ

**Comment by goragodwiriya** [comment]
แก้ไขให้แล้วครับ 
ดาวน์โหลดไฟล์ทั้งหมดไปแทนที่ของเดิมเลยครับ 
(มีอัปเดท)

**Comment by appdisqus** [comment]
สวสดีครับ @goragod 

ผมลองอัพเดตไฟล์ทั้งหมดแล้วพบว่าช่องจำนวนเงินมีการคำนวนส่วนลดผิดนะครับ โดยแทนที่จะลดเป็น % มันลดเป็นจำนวนตัวเลขที่อยู่หน้า % แทนน่ะครับ ยกตัวอย่างเช่นสินค้าตัวหนึ่งถูกตั้งราคาไว้ที่ 8000 บาท ลด 5% แล้วมันควรจะเหลือ 7,600 บาท (หลังบ้านแสดงถูกต้อง) แต่ในหน้าปรินต์ใบเสนอราคากลับกลายเป็นแสดงเป็น 7995 บาทแทน คือเอา 8000 ไปลบ 5 น่ะครับ ตามตัวอย่างรูปที่แนบมาเลยครับ

![test-new](https://user-images.githubusercontent.com/35060517/34549206-a07aca38-f139-11e7-9a32-49cc009fa7a5.png)

รบกวนชี้แนะด้วยนะครับ

ขอบคุณมากครับผม

**Comment by goragodwiriya** [comment]
แก้ไขตามนี้เลยครับ 
https://github.com/goragod/oas/blob/master/modules/inventory/controllers/export.php#L68

บรรทัด 68-71

**Comment by appdisqus** [comment]
@goragod 

ขอบคุณมากครับผม แสดงผลถูกต้องตามสมควรเรียบร้อยครับ ^^

อาจารย์พอจะมีวิธีให้มัน export เป็น pdf ได้แทนการปรินต์ด้วยไหมครับผม พอดีเห็นในคำอธิบายโค๊ดเหมือนจะมี controller สร้าง pdf แต่ไม่แน่ใจว่ามันต้องทำอย่างไรน่ะครับ

ขอบคุณมากครับผม

**Comment by goragodwiriya** [comment]
ได้ครับ โดยการใช้ mpdf 
ทำต่อจากการ export เป็น html ครับ 
(mpdf สามารถสร้าง pdf จาก html ได้) 
ข้อมูลให้ศึกษาจาก mpdf 
เลยครับ

https://github.com/goragod/oas/blob/master/modules/inventory/views/export.php

ข้อมูล HTML อยู่ที่ $template->render();

**Comment by appdisqus** [comment]
@goragod 

รบกวนสอบถามอาจารย์อีกนิดครับว่าหากเราต้องการให้ Product Number (product_id) แสดงในหน้าใบสั่งซื้อด้วย จะต้องแก้ไขส่วนไหนเหรอครับให้มันสามารถดึงรหัสสินค้ามาได้ (เดี๋ยวผมไปจัดการในส่วนของพื้นที่ template ในหน้ายสั่งซื้อต่อเองให้มีที่สำหรับตัวเลขรหัสสินค้าได้ครับ)

ขอบคุณมากครับผม

**Comment by goragodwiriya** [comment]
พอดีมีคำถามคล้ายๆกัน 
https://www.kotchasan.com/forum.html?wbid=3812

ข้อมูลที่ต้องการอยู่แถวๆนี้ 
https://github.com/goragod/oas/blob/master/modules/inventory/controllers/export.php#L57

**Comment by appdisqus** [comment]
@goragod 

ขอบคุณมากครับผม

ตอนนี้ผมเจออีกปัญหาครับ "หัก ภาษี หัก ณ ที่จ่าย/Less W/H Tax" ไม่ถูกนำไปหักลบจาก "Grand Total"

![screen shot 2561-01-09 at 08 59 57](https://user-images.githubusercontent.com/35060517/34701615-dafbbdbc-f51b-11e7-80be-1ca6a3d45b2b.png)

จะเห็นว่าจริงๆ แล้วยอดใน Grand Total จะต้องแสดงเป็น 46,800 (48,150 - 1,350) แต่ว่ามันแสดงเป็นยอดที่ไม่หักลบภาษี ณ ที่จ่ายแทนน่ะครับ

รบกวนด้วยครับผม

**Comment by appdisqus** [comment]
@goragod 

สวัาดีครับ

ผมเจอจุดที่ต้องแก้ไขแล้วครับผม 

ขอบคุณมากครับ

**Comment by appdisqus** [comment]
@goragod 

อาจารย์ครับ ถ้าเราต้องการให้สามารถทำซ้ำ (duplicate) ใบสั่งซื้อหรือใบเสนอราคาได้ เราพอจะเพิ่มฟังก์ชั่นเข้าไปได้ไหมครับ และหากได้เราควรจะแก้ไขที่ไฟล์ไหนดีเหรอครับผม

ขอบคุณมากครับ

**Comment by goragodwiriya** [comment]
ได้ครับ แนะนำให้ดูใน database 
ว่ารายการนั้นๆมีข้อมูลใดบ้าง 
(ทดลองเพิ่มรายการด้วยตัวเองใน 
database ตรงๆ 
ถ้าสามารถทำได้ก็มีโอกาศจะ 
copy ได้)

ส่วนจะทำที่ไหน 
หรือด้วยวิธีไหน 
อันนี้แล้วแต่สะดวกเลยครับ 
(ถ้าทำในตารางจะง่ายสุด 
ดูตัวอย่างพวกคำสั่ง "ลบ" 
ในตาราง 
สามารถทำได้ด้วยวิธีเดียวกัน)
