### ISSUE TITLE
รายการสินค้าขึ้นไม่ตามลำดับที่มีการพิมพ์บันทึกครับ

### ISSUE THREAD

**Issue by appdisqus** [goragod/oas#3]
สวัสดีครับ @goragod 

เจอปัญหารายการสินค้าขึ้นไม่เรียงตามลำดับที่พิมพ์เข้าไปนะครับ (ใบสั่งซื้อ) และไม่ทราบแน่ชัดว่ามันเรียงตามอะไร เหมือนมันสุ่มมั่วไปหมดเลยน่ะครับ ทำให้ส่งผลต่อการตรวจเช็ครายการและการชัดการหาสินค้าของซัพพลายเออร์เพราะว่าเราไม่สามารถจัดเรียงลำดับสินค้าได้ตามกลุ่มสินค้าน่ะครับ สำหรับ PO ที่มีหลายรายการมากมันเรียงลำดับมั่วหมดเลยน่ะครับ

ไม่แน่ใจว่าพอจะแนะนำหรือมีวิธีการแก้ไขได้อย่างไรไหมครับ

ขอบคุณมากครับ

**Comment by goragodwiriya** [comment]
แก้ไขให้แล้วครับ

แนะนำอัปเดททั้งหมดเลยนะครับ 
(นำไฟล์ใหม่ไปแทนที่) 
มีอัปเดทหลายจุด

**Comment by appdisqus** [comment]
@goragod 

ขอบคุณมากครับอาจารย์ เดี๋ยวจะลองอัพเดตดูแล้วจะแจ้งผลนะครับ

ขอบคุณครับ

**Comment by appdisqus** [comment]
@goragod 

ตอนนี้เรียงตามลำดับที่คีย์เข้าไปเรียบร้อยครับอาจารย์

ขออนุญาตสอบถามเพิ่มเติมได้ไหมครับว่าหากอยากสลับตำแหน่งข้อมูลในตารางในหน้าพิมพ์ใบเสนอราคาหรือพิมพ์ใบสั่งซื้อนี่ควรดูที่ไฟลไหนดีเหรอครับ พอดีผมลองดูใน export แล้วมันเหมือนไม่ใช่ที่ๆ รูปแบบการแสดงผลมันอยู่น่ะครับ

ตัวอย่างเช่นในใบสั่งซื้อ หากผมอยากสลับเอาจำนวน ไปไว้หลังราคาต่อหน่วย แทนที่เป็นอยู่ในปัจจุบัน ต้องไปโฟกัสที่ไฟล์ไหนดีเหรอครับ

ขอบคุณครับ

**Comment by goragodwiriya** [comment]
ดูใน inventory/template/
